**Dot Product Example - Ice-cream sales**

In [22]:
import numpy as np
import pandas as pd

In [23]:
np.random.seed(0)
# Number of ice-creams sold
sales_amt = np.random.randint(15, size=(5,3))
# Size is mentioned as 5 rows which specifies '5 days in a week' and 3 columns specifies 'Flavours of Ice-creams'
sales_amt

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [26]:
# Creating weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amt,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Black currant", "Chocolate", "Badam Kulfi"])
weekly_sales

Black currant  Chocolate  Badam Kulfi
Mon               12          5            0
Tues               3         11            3
Wed                7          9            3
Thurs              5          2            4
Fri                7          6            8

In [27]:
# Creating Prices array
prices = np.array([25, 20, 30])
prices

array([25, 20, 30])

In [37]:
# Creating ice-cream_prices DataFrame
icecream_prices = pd.DataFrame(prices.reshape(1, 3),
                             index = ["Price"],
                             columns = ["Black currant", "Chocolate", "Badam Kulfi"])
icecream_prices

Black currant  Chocolate  Badam Kulfi
Price             25         20           30

In [38]:
prices.shape, sales_amt.shape #Both didn't align to perform the dot operation

((3,), (5, 3))

In [39]:
total_sales = prices.dot(sales_amt.T)
total_sales

array([400, 385, 445, 285, 535])

In [40]:
#Create daily_sales
icecream_prices

Black currant  Chocolate  Badam Kulfi
Price             25         20           30

In [41]:
weekly_sales

Black currant  Chocolate  Badam Kulfi
Mon               12          5            0
Tues               3         11            3
Wed                7          9            3
Thurs              5          2            4
Fri                7          6            8

In [42]:
icecream_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [43]:
daily_sales = icecream_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  400   385  445    285  535

In [44]:
weekly_sales

Black currant  Chocolate  Badam Kulfi
Mon               12          5            0
Tues               3         11            3
Wed                7          9            3
Thurs              5          2            4
Fri                7          6            8

In [45]:
weekly_sales["Total (Rs.)"] = daily_sales.T
# Shape of daily_sales is (1, 5)
# We must transpose to add in the weekly_sales report
weekly_sales

Black currant  Chocolate  Badam Kulfi  Total (Rs.)
Mon               12          5            0          400
Tues               3         11            3          385
Wed                7          9            3          445
Thurs              5          2            4          285
Fri                7          6            8          535